### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gillchristian** [gillchristian/listas-web#3]
Backend TODOs: https://github.com/ndelvalle/listas-api/issues/12

## MVP

- [ ] List view (with edit)
- [ ] API: handle different response statuses: `data ApiError = Decoding | Client | Server | Other`
- [ ] API: Use Either instead of Maybe for responses
- [ ] Forms validation
- [ ] Dropdown: Show error & help
- [ ] Dropdown: styles
- [x] Done resources view
- [x] List stats: calculate on API call
- [x] Dashboard: Create resource in line with "Read Next"
- [x] Design styles
- [x] Mark resource as done
- [x] Show list resources on expand
- [x] Extract List as a component
- [x] Extract Create Resource logic as component
- [x] Dropdown: Reset on create
- [x] Create resources
- [x] Show first resource only
- [x] Select component for chosing the list (https://github.com/citizennet/purescript-halogen-select)
- [x] Handle email verification failure

## Nice to have

- [ ] Create resource: open on `ctrl + v` on the dashboard body
- [ ] Create resource: show title and description as "Show more"
- [ ] Create resource: async validate if URL exists
- [ ] Create resource: fetch scraped title from API
- [ ] Dropdown: don't trigger other events (like submit)
- [ ] Dropdown: don't trigger validation of other fields on "Open"
- [ ] Logout (in header)
- [ ] Browser extension
- [ ] Footer
- [ ] Create Resource form should allow to create a new list as well
- [ ] URL validation: URL already exists, remove utm strings (configurable?), check if URL.
- [ ] Create resource: textarea for description
- [ ] Create list: textarea for description
- [ ] Email field on Verify Failure to resend verification email
- [ ] Settings form (preferences & profile changes)
- [ ] Default Avatar URL
- [ ] Fix: `/register` & `/login` show 404 when logged in
- [ ] Add missing dates fields
- [ ] On verify success/failure if user is logged in navigate to Dashboard
- [ ] Dashboard: Filters for empty & completed lists
- [ ] Dashboard: Icons for empty & completed lists
- [ ] Close "Create resource" on ESC
- [ ] GitHub like view of activity (_done_ items per day) on profile

## Nice to have: tech & refactors

- [ ] Use lenses
- [ ] Components library
- [ ] Use Newtypes (ID, Email, Slug, etc)
- [ ] Navigate to `/login` instead of rendering in place (pass a Route to the `redirect` input field)
- [ ] Move _register stuff_ to `AppM`
- [ ] Better name for `navigate_`
- [ ] Use a more expressive type for errors on `FormQuery`
- [ ] Log decoding error on read token on `Main`
- [ ] Register form: `handleQuery` like login
- [ ] How to optimize state in Halogen? (eg. don't fetch again when navigating back to `/discover`)
- [ ] Link component
- [ ] Logging service for production
- [ ] Add parallel capabilities (https://github.com/thomashoneyman/purescript-halogen-realworld/commit/4db3e750773b07bdd97fd908b3fd2de662b84222)
- [x] Dashboard: Refactor code in `LoadLists` & `HandleCreateForm` action handlers
